import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [active,setActive]=useState(true);

  const element=React.createElement('ul',{className:"list"},[
    React.createElement('li',{className:"list-item"},["one"]),
    React.createElement('li',{className:"list-item"},["two"]),
    React.createElement('li',{className:"list-item"},["three"])
  ])

  const changeActive=()=>{
    // setActive((active)=>!active)
    setTimeout(()=>{
      console.log(active)
      setActive((active)=>!active)
    },3000)
  }
  <script>
    window.onload=function(){
      setTimeout(()=>{
        console.log(active)
        setActive((active)=>!active)
      },3000)
    }
  </script>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        {active ?<div className={styles.circles}>
          <div className={styles.circle}></div>
          <div className={styles.circle}></div>
          <div className={styles.circle}></div>
          <div className={styles.content}>loading...</div>
        </div>:null}
        {active ? null:element}
        <button className={styles.button} onClick={changeActive}>ボタン</button>
      </div>
    </div>
  )
}
